rm -rf result_cuts/*_Cen.root
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_data_DoubleEl.root\"\,\"result_cuts/data_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_TTTo2L2Nu2B.root\"\,\"result_cuts/TH2_TTTo2L2Nu2B_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_WW_pythia_filtered.root\"\,\"result_cuts/TH2_DiBWW_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_WZ_pythia_filtered.root\"\,\"result_cuts/TH2_DiBWZ_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_ZZ_pythia_filtered.root\"\,\"result_cuts/TH2_DiBZZ_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_DYJetsToLL_PtZ-100.root\"\,\"result_cuts/TH2_DYJetsPtZ100_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_DYJetsToLL_PtZ-70To100.root\"\,\"result_cuts/TH2_DYJetsPtZ70To100_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_AbelianZPrime_ZH_lljj_M800.root\"\,\"result_cuts/ZPrime_ZH_lljj_M800_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_AbelianZPrime_ZH_lljj_M900.root\"\,\"result_cuts/ZPrime_ZH_lljj_M900_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_AbelianZPrime_ZH_lljj_M1100.root\"\,\"result_cuts/ZPrime_ZH_lljj_M1100_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_AbelianZPrime_ZH_lljj_M1400.root\"\,\"result_cuts/ZPrime_ZH_lljj_M1400_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_AbelianZPrime_ZH_lljj_M1700.root\"\,\"result_cuts/ZPrime_ZH_lljj_M1700_El_Cen.root\"\)
root -b -l -q TH2Fitting/recoXMassCSV.C++\(0\,\"~/XtoZh/delpanjTuple/delpanj_v4_AbelianZPrime_ZH_lljj_M1900.root\"\,\"result_cuts/ZPrime_ZH_lljj_M1900_El_Cen.root\"\)